spring: 
  cloud: 
    stream: 
      bindings: 
        moho-channel: 
          destination: moho-event
          group: moho
          binder: rabbit
      rabbit:
        bindings:
          moho-channel:
            consumer: 
              auto-bind-dlq: true
              dlq-ttl: 10000